name: 'C++ CI'

on:
  push:
    branches:
      - homework-02

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      # - run: sudo apt-get update && sudo apt-get install libboost-test-dev -y
      - run: cmake 02 # -DPATCH_VERSION=${{ github.run_number }} -DWITH_BOOST_TEST=ON
      - run: cmake --build .
      # - run: cmake --build . --target test
      - run: cmake --install .
      - run: diff <(cat ip_filter.tsv | ip_filter | md5sum) <(echo "24e7a7b2270daee89c64d3ca5fb3da1a  -")
